title: Test Site
email: test@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple and elegant theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
permalink: pretty

markdown: kramdown
